name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pipenv
        pipenv install codecov
        pipenv sync -d
        pipenv install --deploy --dev
    - name: Relatório Coverage
      env:
        CODECOV_TOKEN: 'b2d137a5-badd-4346-899d-d986ef3c6d76'
      run: |
        pipenv run codecov